# Generated by Django 4.2 on 2024-05-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
