# Generated by Django 4.2 on 2024-05-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_bb_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
